// Mocks generated by Mockito 5.4.6 from annotations
// in paypal_integration/test/services/mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;
import 'package:paypal_integration/core/services/models/form_data.dart' as _i6;
import 'package:paypal_integration/core/services/network/dio_http_service.dart'
    as _i3;
import 'package:paypal_integration/core/services/network/http_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeResponse_0<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [DioHttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDioHttpService extends _i1.Mock implements _i3.DioHttpService {
  MockDioHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl =>
      (super.noSuchMethod(
            Invocation.getter(#baseUrl),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.getter(#baseUrl),
            ),
          )
          as String);

  @override
  Map<String, String> get headers =>
      (super.noSuchMethod(
            Invocation.getter(#headers),
            returnValue: <String, String>{},
          )
          as Map<String, String>);

  @override
  _i5.Future<_i2.Response<dynamic>> get(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    bool? isAuthenticated = true,
    bool? forceRefresh = false,
    _i2.CancelToken? cancelToken,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {
                #queryParameters: queryParameters,
                #isAuthenticated: isAuthenticated,
                #forceRefresh: forceRefresh,
                #cancelToken: cancelToken,
                #headers: headers,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endpoint],
                  {
                    #queryParameters: queryParameters,
                    #isAuthenticated: isAuthenticated,
                    #forceRefresh: forceRefresh,
                    #cancelToken: cancelToken,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> post(
    String? endpoint, {
    _i6.BaseFormData? formData,
    Map<String, dynamic>? queryParameters,
    _i7.ContentType? contentType = _i7.ContentType.formData,
    bool? isAuthenticated = false,
    _i2.CancelToken? cancelToken,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {
                #formData: formData,
                #queryParameters: queryParameters,
                #contentType: contentType,
                #isAuthenticated: isAuthenticated,
                #cancelToken: cancelToken,
                #headers: headers,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endpoint],
                  {
                    #formData: formData,
                    #queryParameters: queryParameters,
                    #contentType: contentType,
                    #isAuthenticated: isAuthenticated,
                    #cancelToken: cancelToken,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> put(
    String? endpoint,
    _i6.BaseFormData? formData, {
    Map<String, dynamic>? queryParameters,
    bool? isAuthenticated = true,
    _i7.ContentType? contentType = _i7.ContentType.json,
    _i2.CancelToken? cancelToken,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint, formData],
              {
                #queryParameters: queryParameters,
                #isAuthenticated: isAuthenticated,
                #contentType: contentType,
                #cancelToken: cancelToken,
                #headers: headers,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endpoint, formData],
                  {
                    #queryParameters: queryParameters,
                    #isAuthenticated: isAuthenticated,
                    #contentType: contentType,
                    #cancelToken: cancelToken,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<_i2.Response<dynamic>> patch(
    String? endpoint,
    _i6.BaseFormData? formData, {
    Map<String, dynamic>? queryParameters,
    bool? isAuthenticated = true,
    _i7.ContentType? contentType = _i7.ContentType.json,
    _i2.CancelToken? cancelToken,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [endpoint, formData],
              {
                #queryParameters: queryParameters,
                #isAuthenticated: isAuthenticated,
                #contentType: contentType,
                #cancelToken: cancelToken,
                #headers: headers,
              },
            ),
            returnValue: _i5.Future<_i2.Response<dynamic>>.value(
              _FakeResponse_0<dynamic>(
                this,
                Invocation.method(
                  #patch,
                  [endpoint, formData],
                  {
                    #queryParameters: queryParameters,
                    #isAuthenticated: isAuthenticated,
                    #contentType: contentType,
                    #cancelToken: cancelToken,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<_i2.Response<dynamic>>);

  @override
  _i5.Future<String> download(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    void Function(int, int)? onReceiveProgress,
    _i2.CancelToken? cancelToken,
    Map<String, String>? headers,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [endpoint],
              {
                #queryParameters: queryParameters,
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #headers: headers,
              },
            ),
            returnValue: _i5.Future<String>.value(
              _i4.dummyValue<String>(
                this,
                Invocation.method(
                  #download,
                  [endpoint],
                  {
                    #queryParameters: queryParameters,
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #headers: headers,
                  },
                ),
              ),
            ),
          )
          as _i5.Future<String>);

  @override
  _i5.Future<dynamic> delete() =>
      (super.noSuchMethod(
            Invocation.method(#delete, []),
            returnValue: _i5.Future<dynamic>.value(),
          )
          as _i5.Future<dynamic>);
}
